# @format

openapi: 3.0.0
info:
    version: 1.0.0
    title: "Payment Service"
    description: "Payment service allows to create and manage Payments"
servers:
    - description: dev server
      url: http://localhost:4005

tags:
    - name: Payment
      description: Payment service Endpoints

paths:
    /payments:
        post:
            tags: [Payment]
            description: create a new Payment
            requestBody:
                content:
                    "application/json":
                        schema:
                            type: object
                            properties:
                                appointment_id:
                                    type: string
                                    example: ksf12kdfh23kd23
                            required: [appointment_id]
            responses:
                "201":
                    description: payment create successful
                    content:
                        "application/json":
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Patient Registration successful
                                    data:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                example: ksf12kdfh23kd23
                                            appointment_id:
                                                type: string
                                                example: kdf12kdfh23kd23

                                            transaction_id:
                                                type: string
                                                example: null
                                            amount:
                                                type: number
                                                example: 1200
                                            payment_status:
                                                type: string
                                                example: PENDING
                                            created_at:
                                                type: string
                                                format: date-time
                                    links:
                                        type: object
                                        properties:
                                            appointment:
                                                type: string
                                                example: "/appointments/:id"
                "400":
                    $ref: "#/components/responses/400"
                "500":
                    $ref: "#/components/responses/500"
        get:
            description: Retrive a list of Patients
            tags: [Payment]
            parameters:
                - $ref: "#/components/parameters/pageParam"
                - $ref: "#/components/parameters/limitParam"
                - $ref: "#/components/parameters/sortByparam"
            responses:
                "200":
                    description: Get a list of Payment
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    data:
                                        type: array
                                        items:
                                            allOf:
                                                - type: object

                                                  properties:
                                                      id:
                                                          type: string
                                                          example: ksf12kdfh23kd23
                                                      appointment_id:
                                                          type: string
                                                          example: kdf12kdfh23kd23
                                                      payment_method:
                                                          type: string
                                                          example: mobile_baking
                                                      transaction_id:
                                                          type: string
                                                          example: kdf12kdfh23kd23
                                                      amount:
                                                          type: number
                                                          example: 1200
                                                      payment_status:
                                                          type: string
                                                          example: pending
                                                      created_at:
                                                          type: string
                                                          format: date-time

                                                - $ref: "#/components/schemas/Timestamp"
                                    pagination:
                                        $ref: "#/components/schemas/Pagination"
                                    links:
                                        type: object
                                        properties:
                                            self:
                                                type: string
                                                format: url
                                                example: /payments?page=2&limit=5
                                            next:
                                                type: string
                                                format: url
                                                example: /payments?page=3&limit=5
                                            prev:
                                                type: string
                                                format: url
                                                example: /payments?page=1&limit=5
                "400":
                    $ref: "#/components/responses/400"
                "401":
                    $ref: "#/components/responses/401"
                "500":
                    $ref: "#/components/responses/500"

    /payments/{id}:
        get:
            tags: [Payment]
            description: Retrive a single Payment by id
            parameters:
                - $ref: "#/components/parameters/idPathParam"
            responses:
                "200":
                    description: Payment retrive  successful
                    content:
                        "application/json":
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: Payment retrive  successful
                                    data:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                example: ksf12kdfh23kd23
                                            appointment_id:
                                                type: string
                                                example: kdf12kdfh23kd23
                                            payment_method:
                                                type: string
                                                example: mobile_banking
                                            transaction_id:
                                                type: string
                                                example: null
                                            amount:
                                                type: number
                                                example: 1200
                                            payment_status:
                                                type: string
                                                example: pending
                                            created_at:
                                                type: string
                                                format: date-time
                "400":
                    $ref: "#/components/responses/400"
                "500":
                    $ref: "#/components/responses/500"
        delete:
            tags: [Payment]
            description: Retrive a single Payment by id
            parameters:
                - $ref: "#/components/parameters/idPathParam"
            responses:
                "204":
                    description: Payment deleted  successfully
                "400":
                    $ref: "#/components/responses/400"
                "500":
                    $ref: "#/components/responses/500"

    /payments/appointments/{appointment_id}:
        get:
            tags: [Payment]
            description: retrive payment by appointment id
            parameters:
                - $ref: "#/components/parameters/appointmentIdPathParam"
            responses:
                "200":
                    description: payment retrive successful
                    content:
                        "application/json":
                            schema:
                                type: object
                                properties:
                                    message:
                                        type: string
                                        example: payment retrive successful
                                    data:
                                        type: object
                                        properties:
                                            id:
                                                type: string
                                                example: as23sdfksdh34hs

                                            auth_user_id:
                                                type: string
                                                example: ksf12kdfh23kd23
                                            name:
                                                type: string
                                                example: Ashik Mondol
                                            email:
                                                type: string
                                                example: ashik@gmail.com
                                            phone_number:
                                                type: string
                                                example: 01313306149
                                            gender:
                                                type: string
                                                enum:
                                                    - male
                                                    - female
                                                example: male
                                            date_of_birth:
                                                type: string
                                                format: data-time
                                            created_at:
                                                type: string
                                                format: date-time
                                            updated_at:
                                                type: string
                                                format: date-time
                "400":
                    $ref: "#/components/responses/400"
                "500":
                    $ref: "#/components/responses/500"
components:
    schemas:
        Timestamp:
            type: object
            properties:
                createdAt:
                    type: string
                    format: date-time
                updatedAt:
                    type: string
                    format: date-time
            required: [createdAt, updatedAt]
        Pagination:
            type: object
            properties:
                page:
                    type: integer
                    format: int32
                    example: 2
                limit:
                    type: integer
                    format: int32
                    example: 10

                next:
                    type: integer
                    format: int32
                    example: 3
                prev:
                    type: integer
                    format: int32
                    example: 3
                totalPage:
                    type: integer
                    format: int32
                    example: 5
                totalItems:
                    type: integer
                    format: int32
                    example: 400
            required:
                - page
                - limit
                - totalPage
                - totalItems

    responses:
        "400":
            description: "bad request"
            content:
                "application/json":
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                                format: int32
                                example: 400
                            error:
                                type: string
                                example: Bad request
                            data:
                                type: array
                                items:
                                    type: object
                                    properties:
                                        field:
                                            type: string
                                            example: email
                                        message:
                                            type: string
                                            example: invalid credntials
                                        in:
                                            type: string
                                            enum: [query, body]
                                            example: body
        "401":
            description: unauthorized
            content:
                "application/json":
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                                format: int32
                                example: 401
                            error:
                                type: string
                                example: unauthorized
                            message:
                                type: string
                                example: You don't have the right permission

        "500":
            description: Internal Server Error
            content:
                "application/json":
                    schema:
                        type: object
                        properties:
                            code:
                                type: integer
                                format: int32
                                example: 500
                            error:
                                type: string
                                example: internale server Error
                            message:
                                type: string
                                example: We are sorry for the inconvenience. Please try again later
    parameters:
        pageParam:
            in: query
            name: page
            description: current page number
            schema:
                type: integer
                format: int32
                example: 3
        limitParam:
            in: query
            name: limit
            description: maximum items to be returned
            schema:
                type: integer
                format: int32
                example: 10
        sortByparam:
            in: query
            name: sort-type
            description: type of sort (asc or dsc)
            schema:
                type: string
                example: updatedAt
        sortTypeParam:
            in: query
            name: sort_type
            description: type of sort (asc or dsc)
            schema:
                type: string
                enum: [asc, dsc]
                example: dsc
        idPathParam:
            in: path
            name: id
            required: true
            description: item id
            schema:
                type: string
                example: kdsf12ksdf32sdf232
        appointmentIdPathParam:
            in: path
            name: appointment_id
            required: true
            description: appointment id
            schema:
                type: string
                example: ksdf12sd12kl12lq
